### ISSUE TITLE
Error Invalid "keyPath" option supplied

### ISSUE THREAD

**Issue by preetampds** [cuongquay/node-red-contrib-aws-iot#11]
Hi,

Even after maintaining the certifcates as mentioned in the read me . i am getting invalid keypath supplied error.
Versions as below
Node Red : v0.16.2
Node js: v6.10.1

could you please let me know how to resolve this

**Comment by cuongquay** [comment]
Can you see any log like this?

[info] [aws-iot-device:Citus™ Sensor] Attempt to connect to broker with [YourThingName] from: /root/.agent/certs
[info] [aws-iot-device:Citus™ Sensor] Using the certificates that are presented as follows:
[info] [aws-iot-device:Citus™ Sensor] - keyPath : /root/.agent/certs/[YourThingName].private.key
[info] [aws-iot-device:Citus™ Sensor] - certPath : /root/.agent/certs/[YourThingName].cert.pem
[info] [aws-iot-device:Citus™ Sensor] - caPath : /root/.agent/certs/root-CA.crt
[error] [aws-mqtt out:fabfc16b.27232] Error: Invalid "keyPath" option supplied.

**Comment by preetampds** [comment]
yes i am seeing the same log using the correct certificates.

Tried setting in different directory but same issue

**Comment by cuongquay** [comment]
It's just incase there is an incorrect path or your node-red dont have enough permission to read these files because of the different running user. I cannot help you if you dont provide any information here to review.

**Comment by preetampds** [comment]
Thank you for the info,
I changed the directory and now the error is not there. however when i try to publish in the flow it says sending but i am not receiving anything on the aws iot console. The certificates in aws have full policy to subscribe,publish,connect etc..

There are no long logs, i see this only
SEND>[topicname ] Buffer

and while using as input in the flow it stays on subscribing

do i need to install anything extra in the node-red flow

Below is the screenshot
![image](https://cloud.githubusercontent.com/assets/14027808/24446096/91d6ee76-146c-11e7-9bc4-d25ad6a7e00a.png)

**Comment by preetampds** [comment]
Resolved the certificate after creation in aws iot was not active
