### ISSUE TITLE
add support for TLS configuration node

### ISSUE THREAD

**Issue by mblackstock** [cuongquay/node-red-contrib-aws-iot#12]
Rather than storing certificates on the local file system directly, it would be better to use the core TLS node.  This way the certificates needed are handled in the same way as MQTT, HTTP request and other nodes.  In Node-RED 0.17 and later, the certificates will be stored in the credentials file rather than the local file system, making it possible to use this node where no file system access is possible.

**Comment by cuongquay** [comment]
Closed due to no response from contributor for any patch.
