### ISSUE TITLE
How to use this Node?

### ISSUE THREAD

**Issue by baraynavab** [cuongquay/node-red-contrib-aws-iot#16]
Hi,

I am trying to use this node. Maybe I dont know what I am doing. I bring in the output Aws Iot mqtt node. Then I put in what I think is the necessary information it is asking for by clicking the new and put in the information needed such as Endpoint, Thing type, "Things Shadow", Cert folder location. There is something that I am not doing right. I am getting an error "Error: Invalid "keyPath" option supplied.". 

If you can help me with that I really appreciate that. I have attached what I am doing and the error I am getting to the right. 

Thanks
![node red - aws node error](https://user-images.githubusercontent.com/16480130/32622020-9ea1923e-c54f-11e7-9b59-a03597307889.png)

**Comment by cuongquay** [comment]
You are missing client id input. Checkout the readme for details

**Comment by baraynavab** [comment]
Hmm a little bit more info please. Cause I did use the clientID but still didnt get it working.

**Comment by cuongquay** [comment]
It’s not an issue about the source code.
