### ISSUE TITLE
Sending forever

### ISSUE THREAD

**Issue by jjpeet** [cuongquay/node-red-contrib-aws-iot#20]
Hi @cuongquay  
Hi I've setup the node and deployed. I'm not getting any errors logged, but the node reports "sending" and this never changes.

I did have some error logs while setting the node up (had to rename certs as per the documentation), but those are fixed now. So I'm confident errors are being logged...

Any thoughts?
Thx
James

**Comment by cuongquay** [comment]
AWS IoT has changed its core and APIs every 6 months. This code doesn’t work with the new version anymore even using the original aws sdk. You should try the nodejs sdk example if can run, please update this source as your contributor.

Thanks,
