### ISSUE TITLE
Dynamic setting of things names

### ISSUE THREAD

**Issue by zafrirron** [cuongquay/node-red-contrib-aws-iot#21]
Since configuration nodes are static (set once in node red).
and each Iot device needs to have unique ID (name), I could not find a way to distribute software versions for devices without setting the name (in MQTT In node) for each one manually (inside node red IDE + deploy).
As a result there is no way to distribute iot clients devices.

B.T.W my personal very very very ugly (& stupid) solution for this limitation is rewriting the node red software file (the client id name) by node red itself and restarting node red server. this was my only way to distribute...

Any better solution?

**Comment by cuongquay** [comment]
I am sorry to not active for this repo. I almost forget everything about node-red.
