### ISSUE TITLE
MQTT "retain" attribute not supported by AWS IOT

### ISSUE THREAD

**Issue by vielmetti** [cuongquay/node-red-contrib-aws-iot#3]
From http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html

> The MQTT specification provides a provision for the publisher to request that the broker retain the last message sent to a topic and send it to all future topic subscribers. AWS IoT does not support retained messages. If a request is made to retain messages, the connection is disconnected.

This code should not try to set the retain flag, and should clear the retain flag if an attempt is made to set it.

**Comment by cuongquay** [comment]
I updated following your suggestion. Thanks for your reference link.

**Comment by cuongquay** [comment]
Relating to issue#8, the options must be an empty {} to avoid adding chars of qos or retain that will cause the IoT rule is fallen when passing the payload to AWS ElasticSearch. But using with DynamoDB, the payload is parsed OK.

**Comment by vielmetti** [comment]
Interesting. Our downstream database is DynamoDB and so we didn't notice the problem.
