### ISSUE TITLE
Documentation for format of key storage

### ISSUE THREAD

**Issue by vielmetti** [cuongquay/node-red-contrib-aws-iot#5]
To connect to AWS IoT you need to have certs, which are stored in a directory and which have a specific set of names. Document these names (perhaps in the README file, or in the node help) so that people setting this up know what to expect.

**Comment by vielmetti** [comment]
From the help file in the underlying library, https://github.com/aws/aws-iot-device-sdk-js/blob/master/README.md

Default certificate/key file names are as follows:

certificate.pem.crt: your AWS IoT certificate
private.pem.key: the private key associated with your AWS IoT certificate
root-CA.crt: the root CA certificate (available from Symantec here)

**Comment by cuongquay** [comment]
I put it on.
